"""Set of rules to build and test OpenSCAD code through bazel"""

module(
    name = "rules_openscad",
    version = "0.2",
    compatibility_level = 0,
)

bazel_dep(
    name = "bazel_skylib",
    version = "1.7.1",
    dev_dependency = True,
)

bazel_dep(
    name = "stardoc",
    version = "0.8.0",
    dev_dependency = True,
)
